USE `cookbook`;

SELECT ENGINE FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'cookbook' AND TABLE_NAME = 'mail';

SHOW TABLE STATUS LIKE 'mail'\G

SHOW CREATE TABLE mail\G

ALTER TABLE mail ENGINE = MyISAM;

SHOW TABLE STATUS LIKE 'mail'\G

SHOW CREATE TABLE mail\G

ALTER TABLE mail ENGINE = InnoDB;