USE `cookbook`;

DROP TABLE IF EXISTS kjv;

CREATE TABLE kjv
(
	bsect 	ENUM('O', 'N') NOT NULL,
	bname 	VARCHAR(20) NOT NULL,
	bnum	TINYINT	UNSIGNED NOT NULL,
	cnum	TINYINT UNSIGNED NOT NULL,
	vnum 	TINYINT UNSIGNED NOT NULL,
	vtext	TEXT NOT NULL,
	FULLTEXT (vtext)
);

LOAD DATA LOCAL INFILE 'kjv.txt' INTO TABLE kjv;